name: 'Chombo'
description: 'Download and compile Chombo'
inputs:
  chombo_root:
    description: 'Path to chombo root'
    required: false
    default: '/home/runner/chombo'
  compile_opts: 
    description: 'Compile options'
    required: false
    default: 'DIM=2'
runs:
  using: "composite"
  steps:
    - name: Setup environmental variables
      shell: bash
      run: |
        echo "CHOMBO_ROOT=${{ inputs.chombo_root }}" >> $GITHUB_ENV
        echo "CHOMBO_HOME=${{ inputs.chombo_root }}/lib" >> $GITHUB_ENV
        echo "HDF5_PATH=$(echo $HOME)/hdf5-dir" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$(echo $LD_LIBRARY_PATH):$(echo $HDF5_PATH)/lib" >> $GITHUB_ENV

    - name: Update package list
      shell: bash
      run: sudo apt-get update

    - name: Install csh
      shell: bash
      run: sudo apt-get install csh

    - name: Install gfortran
      shell: bash
      run: sudo apt-get install gfortran

    - name: Install lbas etc.
      shell: bash
      run: sudo apt-get install libblas-dev liblapack-dev

    - name: Check package versions
      shell: bash
      run: |
        which gfortran
        gfortran --version
        which make
        make --version
        which g++
        g++ --version
        which perl
        perl --version

    - name: Download and install HDF5
      shell: bash
      run: |
        wget 'https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.21/src/hdf5-1.8.21.tar.gz'
        tar -zxvf hdf5-1.8.21.tar.gz
        cd hdf5-1.8.21
        ./configure --prefix=$HDF5_PATH
        make
        make install
   
    - name: Download Chombo
      shell: bash
      run: |
        git clone https://github.com/applied-numerical-algorithms-group-lbnl/Chombo_3.2.git $CHOMBO_ROOT

    - name: Compile Chombo
      shell: bash
      run: |
        cp ${{ github.action_path }}/Make.defs.local \
          $CHOMBO_HOME/mk/Make.defs.local
        cd $CHOMBO_HOME
        make lib ${{ inputs.compile_opts }}
